export const GET_CHARACTERS = 'GET_CHARACTERS';
export const GET_EPISODES = 'GET_EPISODES';
export const GET_CHARACTER_DETAIL = 'GET_CHARACTER_DETAIL';
export const POST_CHARACTER = 'POST_CHARACTER';
export const FILTER_ORIGIN = 'FILTER_ORIGIN'